language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: scheul93@gmail.com
  api_key:
    secure: QKxBuJ/AAzO/mb4uZFNh9zuGPCbJB75eZXPl4ui015tvMZkfrJr17kpzeHdYrESdcnWkftpAXTBavgjHkyAmeDRu6lnXrbahrleMg4FPIpuAufBFKDMGJq7CH3U4WzsAP53vQqKvl3F7M4SfyF1rNaGYk93Ymke5aZdfEBT5qc1ih1tZtG5PTzi9Q4qRdfhm36l8dYBj6OuhEdPinbBSHK54SYmiPP6RSu/94CORDnXDFWAmas481c0JWB00jy56iJ0lQ5NgTUa1t+Nwox1LbmpGLYYNenXIoKWPgdeltkCTnA16DL29HEEzOis2nWUZsGH4XuVZV+qTJlw0/E2mnr6W5/At9TGEzvvJxN8ub3I7cATCZoUfNP9/2ktapWRTO7Q1xIKHNbVPdL+uERYoz3rEv7ch+/sW9T5oC7oDASwo/ihQM+ykyLdCQiIhz+1F+rdhM60486Lbwz7lU9YlQVvhVRarronqH8wTH071uPZ1/nw1G5yvGjbnL7cBM12McYNVJI1wQYo6/jqEratGUUCgnuSxoesoWUmZyEbH1qdvKUreLn/bB4uvl3FFxFU/IYhL8ShaZfgnk8pP3hVJbvPez/JNyZehZrn52ZHZhQZfTgONwfa3XEanfQp85e6cJKugNT5DqvKITZMNZ9u58t/e3ovn0yW18qp4Q9+3tvM=
  on:
    tags: true
    branch: master
    repo: DEGJS/formValidation-required
